### ISSUE TITLE
Reduce required dependencies to minimum

### ISSUE THREAD

**Issue by tkralphs** [aykutbulut/DisCO#3]
I'm not sure exactly what trail of dependencies leads to this problem, but somehow through the dependency structure of all the projects that DisCO depends on, it seems that there is no way to build DisCO without Ipopt, OsiIpopt, and COLA. I think it should be possible to build without any/all of these projects, especially since at the moment one cannot build DisCO cleanly with Mpi in the presence of Ipopt (at least with Mumps). I think one cannot build Cgl-CONIC or COLA without Ipopt either. Can we reduce the required dependencies for each project down to the bare minimum?

**Comment by aykutbulut** [comment]
I removed COLA from dependencies. Ipopt is a dependency of Cgl-CONIC and used at generating cuts to  warm start OA algorithm. I will keep it as a dependency. It seems MPI build issue with mumps is fixed.

**Comment by aykutbulut** [comment]
I think dependencies are minimal enough. I will close this. Please feel free to open it if you have further ideas on this.
