### ISSUE TITLE
Setting objective cutoff parameter not working

### ISSUE THREAD

**Issue by stephenjmaher** [aykutbulut/DisCO#4]
I am setting the objective cutoff using the parameter Dco_cutoff in the parameter file and via command line arguments, but it doesn't appear to be applied. I have tested the instances 10teams, air03 and misc03 using a cutoff of -10000000.0. The expected behaviour is that the solver should return infeasible. Even using a more reasonable cutoff value, this parameter does not appear to have any effect.

I can not see where the cutoff value is applied in the code. Is this a feature available? If not, could this feature be included?

**Comment by aykutbulut** [comment]
Thanks for taking time to create this issue. cutoff parameter is now implemented in the master branch. I am closing this.

**Comment by aykutbulut** [comment]
One more thing, please get updates for ALPS as well.
